### ISSUE TITLE
没有luci界面出现

### ISSUE THREAD

**Issue by devsea** [muink/luci-app-natter#1]
您好，在尝试您移植的natter for openwrt过程中遇到了luci界面不显示的问题，我的路由器刷的是immortalwrt-18.06-k5.4-snapshot，并使用了此版本相应的SDK编译了相应的IPK文件并安装到路由器，natter在命令行下可以正常使用，但是luci界面不能显示出来。尝试删除luci-indexcache并重启也没有显示。
![n20230607114402](https://github.com/muink/luci-app-natter/assets/12539135/875f6fb3-0ce4-4018-8a27-fb9f8bbdb888)

**Comment by muink** [comment]
这个luci界面是基于luci2开发的
需要至少19.02版本才能正常显示
18.06是不支持的
您可能需要更新您的OpenWRT版本

**Comment by devsea** [comment]
感谢回复，换用21.02正常。
