### ISSUE TITLE
keep_alive_interval issue

### ISSUE THREAD

**Issue by devsea** [muink/luci-app-natter#2]
在默认情况下，缺省的keep_alive_interval设置会造成部分网络下External Port频繁变更的问题，我在使用发现是15分钟变更一次，是否可以增加自定义Keep-alive interval保活设置。
`class Natter(object):
    def __init__(self, source_ip, source_port, test_http = False,
                 keep_alive_host = "www.qq.com", keep_alive_interval = 10, retry_sec = 3, log_level = Logger.INFO):`

**Comment by muink** [comment]
Natter 核心并未提供设置 `keep_alive_interval` 的功能
您需要到核心库提交功能请求 https://github.com/MikeWang000000/Natter/issues

此外 Natter 的缺省 `keep_alive_interval` 是 **10s** [[withconfig](https://github.com/MikeWang000000/Natter/blob/v0.9/natter.py#L822)|[noconfig](https://github.com/MikeWang000000/Natter/blob/v0.9/natter.py#L951)]
您可以暂时在设备中的 `/usr/share/natter/natter.py` 中手动修改
